--DROP TABLE users CASCADE;
--DROP TABLE items CASCADE;
--DROP TABLE bookings CASCADE;
--DROP TABLE item_requests CASCADE;
--DROP TABLE comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar(100) NOT NULL,
email varchar(100) NOT NULL unique
);

CREATE TABLE IF NOT EXISTS item_requests (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
description varchar(255) NOT NULL,
user_id BIGINT,
created timestamp NOT NULL,
CONSTRAINT fk_item_requests_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name varchar(100) NOT NULL unique,
description varchar(255) NOT NULL,
available boolean NOT NULL,
user_id BIGINT,
request_id BIGINT,
CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_items_to_requests FOREIGN KEY(request_id) REFERENCES item_requests(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
start_time timestamp NOT NULL,
end_time timestamp NOT NULL,
item_id BIGINT,
user_id BIGINT,
status varchar(9),
CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_bookings_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
description varchar(255) NOT NULL,
item_id BIGINT,
user_id BIGINT,
created timestamp NOT NULL,
CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT fk_comments_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);





